environment:
  build_version: 1.1.0

version: $(build_version)-{build}

pull_requests:
  do_not_increment_build_number: true
  
configuration: Release

image: Visual Studio 2017

before_build:
- ps: . .\patch-version.ps1 src\stashbox.hangfire.csproj $($env:build_version)

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% stashbox.hangfire.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% stashbox.hangfire.sln
  
after_build:
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\artifacts src\stashbox.hangfire.csproj

test_script:
- dotnet test test\stashbox.hangfire.tests.csproj -c %CONFIGURATION% --no-build
  
artifacts:
- path: artifacts\Stashbox.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true